Add spike to scripts/simulate and make simulate
Signed-off-by: Nathaniel Graff <nathaniel.graff@sifive.com>

diff --git a/scripts/simulate b/scripts/simulate
--- a/scripts/simulate
+++ b/scripts/simulate
@@ -4,6 +4,7 @@ set -e
 set -o pipefail
 
 unset elf
+unset spike
 unset qemu
 unset qemu_config
 unset qemu_options
@@ -12,6 +13,7 @@ do
     case "$1"
     in
     --elf)                   elf="$2";   shift 2;;
+    --spike)               spike="$2";   shift 2;;
     --qemu)                 qemu="$2";   shift 2;;
     --qemu-config)   qemu_config="$2";   shift 2;;
     --qemu-options) qemu_options="$2";   shift 2;;
@@ -24,24 +26,30 @@ then
     echo "$0: --elf is required" >&2
     exit 1
 fi
-if [ "$qemu" == "" ]
+if [ "$qemu" == "" -a "$spike" == "" ]
 then
-    echo "$0: --qemu is required" >&2
+    echo "$0: --qemu or --spike is required" >&2
     exit 1
 else
-    if [ "$qemu_config" == "" ]
+    if [ "$qemu" != "" -a "$qemu_config" == "" ]
     then
-        echo "$0: --qemu_config is required" >&2
+        echo "$0: --qemu_config is required with --qemu option" >&2
+        exit 1
+    fi
+
+    if [ ! -f $qemu_config ] ; then
+        echo "$0: Unable to find QEMU config file ${qemu_config}" >&2
         exit 1
     fi
 fi
 
-if [ ! -f $qemu_config ] ; then
-    echo "$0: Unable to find QEMU config file ${qemu_config}" >&2
-    exit 1
+if [ "$qemu" != "" ] ; then
+    echo "Launching QEMU! Press Ctrl-A, X to exit"
+
+    $qemu -readconfig $qemu_config -kernel $elf -nographic $qemu_options
+elif [ "$spike" != "" ] ; then
+    echo "Launching Spike!"
+
+    $spike $elf
 fi
-
-echo "Launching QEMU! Press Ctrl-A, X to exit"
-
-$qemu -readconfig $qemu_config -kernel $elf -nographic $qemu_options
 
